<a href="https://colab.research.google.com/github/Sanjay0958/Matrix-assignment/blob/main/rock_mine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data collection and data Processing

In [14]:
#loadig dataset into pandas dataframe
sonar_data = pd.read_csv('/content/Copy of sonar data.csv',header = None)

In [15]:
sonar_data.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [16]:
#number of rows and columns
sonar_data.shape

(205, 61)

In [17]:
sonar_data.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,...,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.029299,0.038341,0.043721,0.053820,0.074917,0.104552,0.121872,0.135304,0.179079,0.209558,...,0.016109,0.013511,0.010704,0.010960,0.009195,0.008218,0.007757,0.007918,0.007873,0.006527
std,0.023115,0.033155,0.038649,0.046777,0.055614,0.058582,0.061579,0.085204,0.118844,0.134727,...,0.012082,0.009668,0.007095,0.007321,0.007058,0.005767,0.005797,0.006460,0.006142,0.005057
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013400,0.016300,0.018800,0.024300,0.037000,0.067800,0.083200,0.081300,0.097300,0.114600,...,0.008500,0.007300,0.005000,0.005400,0.004000,0.004400,0.003700,0.003600,0.003700,0.003100
50%,0.022800,0.030800,0.034200,0.044000,0.062000,0.092200,0.108300,0.112300,0.155200,0.183800,...,0.013800,0.011600,0.009500,0.009300,0.007500,0.006800,0.005800,0.005800,0.006300,0.005300
75%,0.036300,0.047800,0.057300,0.063300,0.099500,0.134100,0.153900,0.169400,0.235300,0.269600,...,0.020900,0.016800,0.014900,0.014500,0.012100,0.010500,0.010300,0.010300,0.009800,0.008600
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [18]:
sonar_data[60].value_counts()

M    111
R     94
Name: 60, dtype: int64

In [19]:
#M--> mine R-->rock
sonar_data.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022579,0.029836,0.035457,0.040894,0.060984,0.095917,0.114213,0.118148,0.138441,0.160596,...,0.012279,0.010556,0.009595,0.009514,0.008335,0.007397,0.007676,0.006569,0.006901,0.006052

seperating data and lables

In [20]:
x = sonar_data.drop(columns=60,axis=1)
y=sonar_data[60]
print(x)
print(y)

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
200  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
201  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
202  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
203  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
204  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
200  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
201  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
202  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
203  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
204  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

         57      58      59
0    0.0084  0.0090  0.0032
1    0.0049  0.0052  0.0044
2    0.0164  0.0095  0.0078
3    0.0044  0.0040  0.0117
4    0.0048  0.0107  0.0094
..      ...     ...     ...
200  0.0115  0.0193  0.0157
201  0.0032  0.0062  0.0067
202  0.0138  0.0077  0.0031
203  0.0079  0.0036  0.0048
204  0.0036  0.0061  0.0115

[205 rows x 60 columns]
0      R
1      R
2      R
3      R
4      R
      ..
200    M
201    M
202    M
203    M
204    M
Name: 60, Length: 205, dtype: object

train and test data

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.1,stratify=y,random_state=1)

In [22]:
print(x.shape,x_train.shape,x_test.shape)

(205, 60) (184, 60) (21, 60)

In [ ]:
print(x_train)
print(y_train)

         0       1       2       3       4       5       6       7       8   \
9    0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962
180  0.0096  0.0404  0.0682  0.0688  0.0887  0.0932  0.0955  0.2140  0.2546
122  0.0228  0.0853  0.1000  0.0428  0.1117  0.1651  0.1597  0.2116  0.3295
53   0.0152  0.0102  0.0113  0.0263  0.0097  0.0391  0.0857  0.0915  0.0949
61   0.0071  0.0103  0.0135  0.0494  0.0253  0.0806  0.0701  0.0738  0.0117
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
170  0.0329  0.0216  0.0386  0.0627  0.1158  0.1482  0.2054  0.1605  0.2532
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
84   0.0856  0.0454  0.0382  0.0203  0.0385  0.0534  0.2140  0.3110  0.2837
179  0.0095  0.0308  0.0539  0.0411  0.0613  0.1039  0.1016  0.1394  0.2592
140  0.0516  0.0944  0.0622  0.0415  0.0995  0.2431  0.1777  0.2018  0.2611

         9   ...      50      51      52      53      54      55      56  \
9    0.0251  ...  0.0118  0.0090  0.0223  0.0179  0.0084  0.0068  0.0032
180  0.2952  ...  0.0310  0.0237  0.0078  0.0144  0.0170  0.0012  0.0109
122  0.3517  ...  0.0159  0.0172  0.0191  0.0260  0.0140  0.0125  0.0116
53   0.1504  ...  0.0048  0.0049  0.0041  0.0036  0.0013  0.0046  0.0037
61   0.0898  ...  0.0252  0.0043  0.0048  0.0076  0.0124  0.0105  0.0054
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
170  0.2672  ...  0.0104  0.0095  0.0151  0.0059  0.0015  0.0053  0.0016
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
84   0.2751  ...  0.0128  0.0172  0.0138  0.0079  0.0037  0.0051  0.0258
179  0.3745  ...  0.0357  0.0181  0.0019  0.0102  0.0133  0.0040  0.0042
140  0.1294  ...  0.0456  0.0432  0.0274  0.0152  0.0120  0.0129  0.0020

         57      58      59
9    0.0035  0.0056  0.0040
180  0.0036  0.0043  0.0018
122  0.0093  0.0012  0.0036
53   0.0011  0.0034  0.0033
61   0.0032  0.0073  0.0063
..      ...     ...     ...
170  0.0042  0.0053  0.0074
4    0.0048  0.0107  0.0094
84   0.0102  0.0037  0.0037
179  0.0030  0.0031  0.0033
140  0.0109  0.0074  0.0078

[184 rows x 60 columns]
9      R
180    M
122    M
53     R
61     R
      ..
170    M
4      R
84     R
179    M
140    M
Name: 60, Length: 184, dtype: object

model training ==> logestic algorithm

In [ ]:
model = LogisticRegression()

In [23]:
#training the logestic regression model with trainng data
model1=LogisticRegression().fit(x_train , y_train)

model evalution

In [25]:
#accuracy of traing data
x_train_prediction = model1.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [29]:
print(training_data_accuracy )

0.8260869565217391

In [30]:
#accuracy of test data
x_test_predection = model1.predict(x_test)
test_data_accuracy = accuracy_score(x_test_predection,y_test)

In [31]:
print(test_data_accuracy )

0.7619047619047619

In [32]:
input_data = (0.0177,0.03,0.0288,0.0394,0.063,0.0526,0.0688,0.0633,0.0624,0.0613,0.168,0.3476,0.4561,0.5188,0.6308,0.7201,0.5153,0.3818,0.2644,0.3345,0.4865,0.6628,0.7389,0.9213,1,0.775,0.5593,0.6172,0.8635,0.6592,0.477,0.4983,0.333,0.3076,0.2876,0.2226,0.0794,0.0603,0.1049,0.0606,0.153,0.0983,0.1643,0.1901,0.1107,0.1917,0.1467,0.0392,0.0356,0.027,0.0168,0.0102,0.0122,0.0044,0.0075,0.0124,0.0099,0.0057,0.0032,0.0019)

#changing the input data into numpy array
input_data_as_numpy_array = np.asarray(input_data)

In [33]:
# reshape the np array as we are predection for one instance
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)
prediction = model1.predict(input_data_reshape)
print(prediction)

if(prediction[0]=='R'):
  print("it is rock")
else:
   print("it is mine")

['R']
it is rock